### PR TITLE
add easy db upgrade to fingerbank perl lib

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
add easy db upgrade to fingerbank perl lib

# Impacts
Database upgrade and initialization

### CODE REVIEW

**Comment by julsemaan** [comment]
Also requires the following new dependency
ftp://rpmfind.net/linux/dag/redhat/el6/en/x86_64/dag/RPMS/perl-SQL-Translator-0.11007-1.el6.rf.noarch.rpm

**Comment by dwlfrth** [comment]
Is that new dependancy part of the PacketFence repo ?
If not, should we add it ?
Should it also be part of the .spec (RHEL) / control (Debian) file ?

**Comment by julsemaan** [comment]
I will add it to the spec file.

@fdurand or @dwlfrth can you add it to the repos ?

**Comment by julsemaan** [comment]
Here is the debian package : 
http://ftp.us.debian.org/debian/pool/main/libs/libsql-translator-perl/libsql-translator-perl_0.11011-1_all.deb

**Comment by dwlfrth** [comment]
Are both added to the repo ?
Missing refenrence in debian/control file

**Comment by dwlfrth** [comment]
RHEL package is in devel repo, will wait for @fdurand to handle the one for Debian :)

**Pull request merged**
