### PR TITLE
Feature/dhcpv6 perllib

### PR DESCRIPTION
**Pull request by julsemaan**
# Description
Adds DHCPv6 handling to the Fingerbank perl library

# Impacts
All matching in library

# Dependencies
#24 (as it contains the rework of the lib)

### CODE REVIEW

**Comment by dwlfrth** [comment]
Not sure to understand why that much of duplicate (and obsolete since #24 has been retouched)...

**Comment by julsemaan** [comment]
Fixed.
Ready for zi review

**Comment by dwlfrth** [comment]
Would require an "update db" script :/

**Comment by julsemaan** [comment]
Something to look at : 
http://search.cpan.org/dist/DBIx-Class/lib/DBIx/Class/Schema/Versioned.pm

**Comment by dwlfrth** [comment]
Should this be implemented before merging ?

**Comment by julsemaan** [comment]
Not sure.

In the end, we need to test the feature it provides now.

The upgrade part can come afterwards and will be easy to test.

**Pull request merged**
